# TODO Make this work.

desc "Setup core"
task "setup-core" do
  'bash 00-core.sh'
  'bash 10-misc.sh'
end  

desc "Setup Ruby & Rubygems"
task "setup-ruby" => ["setup-core"] do
  'sh 05-ruby-rvm.sh'
end

desc "Setup everything"
task "setup-all" => ["setup-core", "setup-ruby"]